# Generated by Django 6.0.5 on 2026-05-20 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('PICKUP', 'Pick-up'), ('CAMION_5T', 'Camion 5t'), ('CAMION_8T', 'Camion 8t'), ('CAMION_10T', 'Camion 10t'), ('CAMION_15T', 'Camion 15t')], max_length=15)),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('annee', models.PositiveSmallIntegerField()),
                ('capacite_tonnes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_MISSION', 'En mission'), ('EN_PANNE', 'En panne'), ('INDISPONIBLE', 'Indisponible')], default='DISPONIBLE', max_length=15)),
                ('assurance_expiry', models.DateField()),
                ('visite_expiry', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicules/')),
                ('est_actif', models.BooleanField(default=True)),
                ('transporteur', models.ForeignKey(limit_choices_to={'role': 'TRANSPORTER'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'db_table': 'vehicules',
            },
        ),
        migrations.CreateModel(
            name='MissionTransport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=15)),
                ('ville_depart', models.CharField(max_length=100)),
                ('ville_arrivee', models.CharField(max_length=100)),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_depart', models.DateTimeField(blank=True, null=True)),
                ('date_arrivee', models.DateTimeField(blank=True, null=True)),
                ('note', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mission_transport', to='orders.commande')),
                ('transporteur', models.ForeignKey(limit_choices_to={'role': 'TRANSPORTER'}, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='transport.vehicule')),
            ],
            options={
                'db_table': 'missions_transport',
                'ordering': ['-created_at'],
            },
        ),
    ]
