# Generated by Django 6.0.5 on 2026-06-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='carte_grise',
            field=models.FileField(blank=True, null=True, upload_to='vehicules/carte_grise/'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicules/photos/'),
        ),
    ]
