# Generated by Django 5.2.15 on 2026-06-12 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_add_carte_grise_vehicule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifLivraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ville_depart', models.CharField(max_length=100)),
                ('ville_arrivee', models.CharField(max_length=100)),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_actif', models.BooleanField(default=True)),
                ('transporteur', models.ForeignKey(limit_choices_to={'role': 'TRANSPORTER'}, on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_livraison', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tarifs_livraison',
                'ordering': ['ville_depart', 'ville_arrivee'],
                'unique_together': {('transporteur', 'ville_depart', 'ville_arrivee')},
            },
        ),
    ]
