# Generated by Django 5.2.15 on 2026-06-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_tarif_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='missiontransport',
            name='delai_livraison_jours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
