# Generated by Django 5.2.15 on 2026-06-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_add_delai_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='missiontransport',
            name='delai_livraison_unite',
            field=models.CharField(blank=True, choices=[('HEURES', 'Heure(s)'), ('JOURS', 'Jour(s)'), ('MOIS', 'Mois')], default='JOURS', max_length=10),
        ),
    ]
