# Generated by Django 6.0.5 on 2026-05-20 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('solde_bloque', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_recu', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_retire', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('est_actif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=25, unique=True)),
                ('type', models.CharField(choices=[('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait'), ('PAIEMENT', 'Paiement commande'), ('RECEPTION', 'Réception paiement'), ('COMMISSION', 'Commission AgroConnect'), ('REMBOURSEMENT', 'Remboursement'), ('BLOCAGE', 'Blocage séquestre'), ('LIBERATION', 'Libération séquestre')], max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('SUCCES', 'Succès'), ('ECHEC', 'Échec'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=15)),
                ('mode', models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('MOOV', 'Moov Money'), ('CELTIS', 'Celtis Cash'), ('BANK', 'Virement bancaire'), ('INTERNE', 'Transfert interne')], default='INTERNE', max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frais', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, default='')),
                ('commande_id', models.UUIDField(blank=True, null=True)),
                ('numero_mobile', models.CharField(blank=True, default='', max_length=20)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
