# Generated by Django 6.0.6 on 2026-07-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_platform_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait'), ('PAIEMENT', 'Paiement commande'), ('RECEPTION', 'Réception paiement'), ('COMMISSION', 'Commission AgroSaaNuu'), ('REMBOURSEMENT', 'Remboursement'), ('BLOCAGE', 'Blocage séquestre'), ('LIBERATION', 'Libération séquestre')], max_length=20),
        ),
    ]
