# Generated by Django 6.0.5 on 2026-05-20 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsFidelite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_actuels', models.PositiveIntegerField(default=0)),
                ('points_totaux', models.PositiveIntegerField(default=0)),
                ('points_utilises', models.PositiveIntegerField(default=0)),
                ('niveau', models.CharField(choices=[('BRONZE', 'Bronze'), ('ARGENT', 'Argent'), ('OR', 'Or'), ('PLATINE', 'Platine')], default='BRONZE', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_fidelite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'points_fidelite',
            },
        ),
        migrations.CreateModel(
            name='HistoriquePoints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('GAIN', 'Gain'), ('UTILISATION', 'Utilisation'), ('EXPIRATION', 'Expiration')], max_length=15)),
                ('points', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('commande_id', models.UUIDField(blank=True, null=True)),
                ('points_fidelite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='loyalty.pointsfidelite')),
            ],
            options={
                'db_table': 'historique_points',
                'ordering': ['-created_at'],
            },
        ),
    ]
