# Generated by Django 6.0.5 on 2026-05-20 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_produit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frais_paiement', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_vendeur', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('MOOV', 'Moov Money'), ('CELTIS', 'Celtis Cash'), ('BANK', 'Virement bancaire')], max_length=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('EN_PREPARATION', 'En préparation'), ('EN_LIVRAISON', 'En cours de livraison'), ('LIVREE', 'Livrée'), ('CONFIRMEE_RECEPTION', 'Réception confirmée'), ('ANNULEE', 'Annulée'), ('LITIGE', 'En litige')], default='EN_ATTENTE', max_length=30)),
                ('adresse_livraison', models.TextField()),
                ('telephone_livraison', models.CharField(max_length=20)),
                ('note_acheteur', models.TextField(blank=True, default='')),
                ('note_livraison', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('commentaire_livraison', models.TextField(blank=True, default='')),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('acheteur', models.ForeignKey(limit_choices_to={'role': 'BUYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='commandes_acheteur', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='products.produit')),
                ('vendeur', models.ForeignKey(limit_choices_to={'role': 'SELLER'}, on_delete=django.db.models.deletion.CASCADE, related_name='commandes_vendeur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LitigeCommande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', "En cours d'examen"), ('RESOLU', 'Résolu'), ('FERME', 'Fermé')], default='OUVERT', max_length=20)),
                ('resolution', models.TextField(blank=True, default='')),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='litige', to='orders.commande')),
                ('plaignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litiges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'litiges_commande',
                'ordering': ['-created_at'],
            },
        ),
    ]
