# Generated by Django 5.2.14 on 2026-06-01 10:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_escrow_payment_system'),
    ]

    operations = [
        # AlterField ne peut pas convertir bigint -> uuid sur PostgreSQL (pas de cast valide),
        # contrairement à SQLite qui laissait passer silencieusement. Ces tables étant vides
        # à ce stade de l'historique des migrations, on supprime puis recrée la colonne id.
        migrations.RemoveField(model_name='paiement', name='id'),
        migrations.AddField(
            model_name='paiement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(model_name='retaitvendeur', name='id'),
        migrations.AddField(
            model_name='retaitvendeur',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
