# Generated by Django 5.2.15 on 2026-06-12 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_commande_noter_vendeur_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='confirme_acheteur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='confirme_transporteur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='confirme_vendeur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='transporteur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TRANSPORTER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_transporteur', to=settings.AUTH_USER_MODEL),
        ),
    ]
