# Generated by Django 5.2.15 on 2026-06-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_commande_transporteur_confirmations'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='confirme_preparation_vendeur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='confirme_reception_vendeur',
            field=models.BooleanField(default=False),
        ),
    ]
