# Generated by Django 5.2.15 on 2026-06-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_add_vendor_workflow_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='panier_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
