# Generated by Django 5.2.15 on 2026-06-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_panier_id_to_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='nom_commande',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
