# Generated by Django 5.2.15 on 2026-06-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_nom_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='groupe_vendeur_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
