# Generated by Django 5.2.14 on 2026-06-01 10:28

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BJ', unique=True)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('cip', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('role', models.CharField(choices=[('BUYER', 'Acheteur'), ('SELLER', 'Vendeur'), ('TRANSPORTER', 'Transporteur'), ('ADMIN', 'Administrateur')], default='BUYER', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('BANNED', 'Banni'), ('PENDING', 'En attente')], default='PENDING', max_length=20)),
                ('ville', models.CharField(blank=True, default='', max_length=100)),
                ('adresse', models.TextField(blank=True, default='')),
                ('bio', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('cip_verifie', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('type', models.CharField(choices=[('INSCRIPTION', 'Inscription'), ('PAIEMENT', 'Paiement'), ('REINIT_MDP', 'Réinitialisation')], max_length=20)),
                ('est_utilise', models.BooleanField(default=False)),
                ('expire_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_ventes', models.PositiveIntegerField(default=0)),
                ('est_certifie', models.BooleanField(default=False)),
                ('numero_immatriculation', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_impot', models.CharField(blank=True, max_length=50, null=True)),
                ('cip_photo', models.ImageField(blank=True, null=True, upload_to='documents/cip/')),
                ('licence_business', models.FileField(blank=True, null=True, upload_to='documents/business_license/')),
                ('kyc_status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('compte_bancaire', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_titulaire_compte', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seller_profiles',
            },
        ),
        migrations.CreateModel(
            name='TransporterProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_missions', models.PositiveIntegerField(default=0)),
                ('est_disponible', models.BooleanField(default=True)),
                ('zones', models.JSONField(default=list)),
                ('est_certifie', models.BooleanField(default=False)),
                ('cip_photo', models.ImageField(blank=True, null=True, upload_to='documents/cip/')),
                ('kyc_status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('compte_bancaire', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_titulaire_compte', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transporter_profiles',
            },
        ),
    ]
