# Generated by Django 6.0.6 on 2026-07-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_motif_rejet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='type',
            field=models.CharField(choices=[('INSCRIPTION', 'Inscription'), ('CONNEXION', 'Connexion'), ('PAIEMENT', 'Paiement'), ('REINIT_MDP', 'Réinitialisation')], max_length=20),
        ),
    ]
