# Generated by Django 6.0.5 on 2026-05-21 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriquePrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_marche', models.DateField()),
            ],
            options={
                'db_table': 'historique_prix',
                'ordering': ['date_marche'],
            },
        ),
        migrations.CreateModel(
            name='PrixMarche',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unite', models.CharField(choices=[('TONNE', 'Tonne'), ('KG', 'Kilogramme'), ('SAC_50KG', 'Sac 50kg')], default='TONNE', max_length=15)),
                ('variation', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date_marche', models.DateField()),
                ('source', models.CharField(blank=True, default='AgroConnect', max_length=200)),
                ('est_valide', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Prix du marché',
                'verbose_name_plural': 'Prix du marché',
                'db_table': 'prix_marche',
                'ordering': ['-date_marche', 'produit'],
            },
        ),
        migrations.CreateModel(
            name='AlertePrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit', models.CharField(max_length=100)),
                ('ville', models.CharField(blank=True, default='', max_length=100)),
                ('prix_seuil', models.DecimalField(decimal_places=2, max_digits=12)),
                ('est_active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_prix', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alertes_prix',
                'ordering': ['-created_at'],
            },
        ),
    ]
