# Generated by Django 6.0.6 on 2026-07-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prixmarche',
            name='source',
            field=models.CharField(blank=True, default='AgroSaaNuu', max_length=200),
        ),
    ]
