# Generated by Django 6.0.5 on 2026-05-20 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('COMMANDE', 'Commande'), ('PAIEMENT', 'Paiement'), ('LIVRAISON', 'Livraison'), ('SYSTEME', 'Système'), ('PROMOTION', 'Promotion'), ('ALERTE_PRIX', 'Alerte prix')], default='SYSTEME', max_length=20)),
                ('est_lue', models.BooleanField(default=False)),
                ('lien', models.CharField(blank=True, default='', max_length=200)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
